container:
  dockerfile: Dockerfile-test
  cpu: 1
  #memory: 8
  # image: node:latest

#lint_task:      
#  node_modules_cache:
#    folder: node_modules
#    fingerprint_script: cat package-lock.json
#    populate_script: npm ci
#  test_script: npm run lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: MONGOMS_DOWNLOAD_MIRROR="http://downloads.mongodb.org" MONGOMS_VERSION="4.0.5" MONGOMS_DISABLE_POSTINSTALL=1 npm ci
  test_script: npm test -- --verbose ./__tests__/about.spec.js ./server/api/person/__tests__/emailperson.spec.js ./server/services/email/__tests__/email.spec.js ./server/api/person/__tests__/person.spec.js
  # ./server/api/organisation/__tests__/organisation.spec.js ./server/api/interest/__tests__/interest.spec.js ./server/api/health/__tests__/health.spec.js ./server/api/opportunity/__tests__/opportunity.spec.js ./lib/__test__/apiCaller.spec.js ./lib/auth/__test__/auth.spec.js ./node_modules/next-redux-wrapper/lib/index.spec.js ./node_modules/next-redux-wrapper/es6/index.spec.js ./node_modules/json-schema-traverse/spec/index.spec.js ./components/__tests__/Navigation.spec.js ./components/__tests__/Header.spec.js ./components/__tests__/Footer.spec.js ./components/examples/__tests__/Hello.spec.js ./components/examples/__tests__/LessStyled.spec.js ./components/examples/__tests__/AntdType.spec.js ./components/examples/__tests__/IntlDemo.spec.js ./components/testredux/__tests__/RealReduxStoreTest.spec.js ./components/testredux/__tests__/MockReduxStoreTest.spec.js ./components/Op/__tests__/OpDetailForm.spec.js ./components/Op/__tests__/OpCard.spec.js ./components/Op/__tests__/OpListSection.spec.js ./components/Op/__tests__/OpDetail.spec.js ./components/Org/__tests__/OrgCard.spec.js ./components/Org/__tests__/OrgList.spec.js

other_test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: MONGOMS_DOWNLOAD_MIRROR="http://downloads.mongodb.org" MONGOMS_VERSION="4.0.5" MONGOMS_DISABLE_POSTINSTALL=1 npm ci
  test_script: node node_modules/ava/cli.js --verbose ./__tests__/about.spec.js ./server/api/person/__tests__/emailperson.spec.js ./server/services/email/__tests__/email.spec.js ./server/api/person/__tests__/person.spec.js


#  `find . -name '*.spec.js'`

# test_docker_builder: 
#   only_if: $CIRRUS_TAG != ''
#   depends_on: 
#     - test
#     - lint
#   build_script: docker build --tag vly-test:latest -f Dockerfile-test
