FROM node:12 as base
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PORT 3122
EXPOSE 3122

ARG RAYGUN_EXPRESS_SERVER_API_KEY
ENV RAYGUN_EXPRESS_SERVER_API_KEY=${RAYGUN_EXPRESS_SERVER_API_KEY}
ARG RAYGUN_REACT_CLIENT_API_KEY
ENV RAYGUN_REACT_CLIENT_API_KEY=${RAYGUN_REACT_CLIENT_API_KEY}

FROM base as production_build
ENV NODE_ENV=production
COPY . .
RUN npm ci --production
RUN npm run prod-build

FROM node:12-alpine as production
ARG BUILD_REVISION=local-build
ARG BUILD_BADGR_USERNAME
ENV BADGR_USERNAME=${BUILD_BADGR_USERNAME}
ARG BUILD_BADGR_PASSWORD
ENV BADGR_PASSWORD=${BUILD_BADGR_PASSWORD}
ARG BUILD_SMTP_ID
ENV SMTP_ID=${BUILD_SMTP_ID}
ARG BUILD_AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${BUILD_AWS_SECRET_ACCESS_KEY}
ARG BUILD_AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${BUILD_AWS_ACCESS_KEY_ID}
ARG BUILD_SMTP_PWD
ENV SMTP_PWD=${BUILD_SMTP_PWD}
ARG BUILD_VLY_PRIVATE_KEY
ENV VLY_PRIVATE_KEY=${BUILD_VLY_PRIVATE_KEY}
ENV REVISION=${BUILD_REVISION}
ENV NODE_ENV=production
ENV APP_URL=${BUILD_APP_URL}
COPY --from=production_build /usr/src/app /voluntarily
WORKDIR /voluntarily
CMD ["npm", "start" ]

FROM base as development
ENV NODE_ENV=development
ENV MONGOMS_DOWNLOAD_MIRROR="http://downloads.mongodb.org"
ENV MONGOMS_VERSION="v4.0-latest"
COPY . ./
RUN npm install
CMD ["npm", "run", "dev"]
