version: '3'
services:
  web:
    image: 585172581592.dkr.ecr.ap-southeast-1.amazonaws.com/vly2-alpha:master
    ports:
      - "${WEB_PORT:-80}:3122"
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: voluntarily
    environment:
      APP_URL: https://alpha.voluntarily.nz
      NODE_ENV: production



