FROM node:12 as base
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PORT 3122
EXPOSE 3122

FROM base as test
ENV NODE_ENV test
ENV MONGOMS_DOWNLOAD_MIRROR="http://downloads.mongodb.org"
ENV MONGOMS_VERSION="4.0.5"
ENV MONGOMS_DISABLE_POSTINSTALL=1
ENV CI=true
COPY . ./
RUN npm ci
CMD ["npm", "run", "test"]
