module.exports = [
  'Ahipara',
  'Albany',
  'Albany Heights',
  'Alicetown',
  'Annesbrook',
  'Aoraki/Mount Cook',
  'Aotea',
  'Ascot Park',
  'Atawhai',
  'Avalon',
  'Bayswater',
  'Bayview',
  'Beach Haven',
  'Belmont',
  'Birchville',
  'Birkdale',
  'Birkenhead',
  'Bishopdale',
  'Boulcott',
  'Brooklands',
  'Brown Owl',
  'Browns Bay',
  'Calton Hill',
  'Camborne',
  'Campbells Bay',
  'Cannons Creek',
  'Castor Bay',
  'Challis',
  'Chatswood',
  'Clyde Hill',
  'Colac Bay/Ōraka',
  'Cracroft',
  'Days Bay',
  'Devonport',
  'Dodson Valley',
  'Eastbourne',
  'Elsdon',
  'Enner Glynn',
  'Fairfield',
  'Fairview Heights',
  'Featherston',
  'Fernhill',
  'Flat Bush',
  'Forrest Hill',
  'Foxton Beach',
  'Glenfield',
  'Gracefield',
  'Granity',
  'Greenhithe',
  'Greta Valley',
  'Greytown',
  'Haast',
  'Haast Beach',
  'Hanmer Springs',
  'Harbour View',
  'Harington Point',
  'Haumoana',
  'Hauraki',
  'Hāwera',
  'Heretaunga',
  'Hikurangi',
  'Hillcrest',
  'Kaikohe',
  'Kaikōura',
  'Karori',
  'Karori West',
  'Katikati',
  'Kawakawa',
  'Kawerau',
  'Kawhia',
  'Kelson',
  'Kenepuru',
  'Kerikeri',
  'Kihikihi',
  'Kingsley Heights',
  'Korokoro',
  'Kumeū',
  'Kuratau',
  'Lake Ohau Alpine Village',
  'Long Bay',
  'Lookout Point',
  'Lowry Bay',
  'Lucas Heights',
  'Māhina Bay',
  'Mairangi Bay',
  'Makarewa',
  'Mangawhai Heads',
  'Māngere',
  'Māngere Bridge',
  'Māngere East',
  'Manor Park',
  'Manukau City Centre',
  'Manurewa East',
  'Maraenui',
  'Martinborough',
  'Marybank',
  'Massey',
  'Matamata',
  'Matatā',
  'Maungaraki',
  'McLaren Park',
  'Milford',
  'Milson',
  'Minginui',
  'Moana',
  'Moerewa',
  'Monaco',
  'Mosgiel',
  'Motueka',
  'Motuoapa',
  'Mount Maunganui',
  'Murchison',
  'Murrays Bay',
  'Murupara',
  'Narrow Neck',
  'Nelson East',
  'Nelson South',
  'New Windsor',
  'Ngāruawāhia',
  'Ngongotahā',
  'Normandale',
  'Northcote',
  'Northcote Point',
  'Northcross',
  'Ōakura',
  'Ocean Grove',
  'Ocean View',
  'Ohariu',
  'Ohinemutu',
  'Okura',
  'Onehunga',
  'Onekawa',
  'Ōpōtiki',
  'Ōpunake',
  'Ōtāhuhu',
  'Ōtaki',
  'Ōtaki Beach',
  'Ōtara',
  'Oteha',
  'Otematata',
  'Otūmoetai',
  'Ōwhata',
  'Ōwhiro Bay',
  'Paekākāriki',
  'Paeroa',
  'Paihia',
  'Papakōwhai',
  'Papakura',
  'Papamoa Beach',
  'Papatoetoe',
  'Parakai',
  'Paraparaumu',
  'Paraparaumu Beach',
  'Paremata',
  'Paremoremo',
  'Pāuatahanui',
  'Pinehaven',
  'Pinehill',
  'Plimmerton',
  'Point Howard',
  'Pōkeno',
  'Porirua City Centre',
  'Pukekohe',
  'Pukerua Bay',
  'Putāruru',
  'Raetihi',
  'Rakaia',
  'Rangitata',
  'Rānui',
  'Raumati Beach',
  'Remuera',
  'Richmond',
  'Riverstone Terraces',
  'Riverton/Aparima',
  'Rosedale',
  'Rothesay Bay',
  'Rotoehu Forest Village',
  'Schnapper Rock',
  'Seaview',
  'Silverstream',
  'Solway',
  'St Albans',
  'Stanley Point',
  'St Clair Park',
  'St Johns',
  'Stokes Valley',
  'Stonefields',
  'Summerhill',
  'Sunnynook',
  'Sunshine',
  'Tāhunanui',
  'Taitā',
  'Takapuna',
  'Takapūwāhia',
  'Taumarunui',
  'Taupō',
  'Tauranga Central',
  'Tauranga South',
  'Te Aro',
  'Te Aroha',
  'Te Atatū Peninsula',
  'Te Atatū South',
  'Te Awamutu',
  'Te Awanga',
  'Temple View',
  'Timberlea',
  'Tīrau',
  'Tirohanga',
  'Tītahi Bay',
  'Tokoroa Central',
  'Torbay',
  'Tōtara Park',
  'Totara Vale',
  'Trentham',
  'Tuakau',
  'Tūī Glen',
  'Tūrangi',
  'Twizel',
  'Unsworth Heights',
  'Upper Hutt',
  'Waiake',
  'Waimauku',
  'Wainuiomata',
  'Wai o Taiki Bay',
  'Waiouru',
  'Waipukurau',
  'Wairau Valley',
  'Waitakere',
  'Waitangirua',
  'Waitara',
  'Wallaceville',
  'Wanaka',
  'Washington Valley',
  'Waterloo',
  'Wesley',
  'Westgate',
  'Whakarewarewa',
  'Whakatāne',
  'Whangamatā',
  'Whangaparāoa',
  'Wharewaka',
  'Whataroa',
  'Whitby',
  'Windsor Park',
  'Wiri',
  'Woburn',
  'York Bay'
]
