// for now, this is hardcoded to all TLAs and regions in NZ
const regions = [
  {
    name: 'Canterbury',
    containedTerritories: [
      'Addington, Canterbury',
      'Akaroa, Canterbury',
      'Allenton, Canterbury',
      'Andrewville, Canterbury',
      'Aoraki/Mount Cook, Canterbury',
      'Aranui, Canterbury',
      'Ashburton, Canterbury',
      'Avondale, Canterbury',
      'Avonhead, Canterbury',
      'Avonside, Canterbury',
      'Balmoral Hill, Canterbury',
      'Beckenham, Canterbury',
      'Bexley, Canterbury',
      'Bishopdale, Canterbury',
      'Bromley, Canterbury',
      'Broomfield, Canterbury',
      'Burnside, Canterbury',
      'Burwood, Canterbury',
      'Casebrook, Canterbury',
      'Cashmere, Canterbury',
      'Christchurch, Canterbury',
      'Church Bay, Canterbury',
      'Clifton, Canterbury',
      'Cracroft, Canterbury',
      'Dallington, Canterbury',
      'Fendalton, Canterbury',
      'Gleniti, Canterbury',
      'Glenwood, Canterbury',
      'Grantlea, Canterbury',
      'Greta Valley, Canterbury',
      'Halswell, Canterbury',
      'Hampstead, Canterbury',
      'Hanmer, Canterbury',
      'Hanmer Springs, Canterbury',
      'Harewood, Canterbury',
      'Heathcote Valley, Canterbury',
      'Hei Hei, Canterbury',
      'Highfield, Canterbury',
      'Hillmorton, Canterbury',
      'Hillsborough, Canterbury',
      'Hoon Hay, Canterbury',
      'Hornby, Canterbury',
      'Huntsbury, Canterbury',
      'Ilam, Canterbury',
      'Islington, Canterbury',
      'Kensington, Canterbury',
      'Linwood, Canterbury',
      'Lyttelton, Canterbury',
      'Mairehau, Canterbury',
      'Maori Hill, Canterbury',
      'Marchwiel, Canterbury',
      'Merivale, Canterbury',
      'Middleton, Canterbury',
      'Moncks Spur, Canterbury',
      'Mount Cook, Canterbury',
      'Mount Pleasant, Canterbury',
      'Murray Aynsley, Canterbury',
      'Netherby, Canterbury',
      'New Brighton, Canterbury',
      'North Linwood, Canterbury',
      'North New Brighton, Canterbury',
      'Northcote, Canterbury',
      'Oaklands, Canterbury',
      'Opawa, Canterbury',
      'Papanui, Canterbury',
      'Parklands, Canterbury',
      'Parkside, Canterbury',
      'Phillipstown, Canterbury',
      'Puhuka, Canterbury',
      'Rakaia, Canterbury',
      'Rangitata, Canterbury',
      'Redcliffs, Canterbury',
      'Redwood, Canterbury',
      'Riccarton, Canterbury',
      'Richmond, Canterbury',
      'Richmond Hill, Canterbury',
      'Russley, Canterbury',
      'Saint Martins, Canterbury',
      'Scarborough, Canterbury',
      'Seaview, Canterbury',
      'Shirley, Canterbury',
      'Sockburn, Canterbury',
      'Somerfield, Canterbury',
      'South New Brighton, Canterbury',
      'South Rakaia, Canterbury',
      'South Township, Canterbury',
      'Southshore, Canterbury',
      'Spreydon, Canterbury',
      'St Albans, Canterbury',
      'St Andrews Hill, Canterbury',
      'Sumner, Canterbury',
      'Sydenham, Canterbury',
      'Timaru, Canterbury',
      'Tinwald, Canterbury',
      'Twizel, Canterbury',
      'Upper Riccarton, Canterbury',
      'Waimairi Beach, Canterbury',
      'Waimataitai, Canterbury',
      'Waimate, Canterbury',
      'Wainoni, Canterbury',
      'Waltham, Canterbury',
      'Washdyke, Canterbury',
      'Watlington, Canterbury',
      'West End, Canterbury',
      'Woolston, Canterbury'
    ]
  },
  {
    name: 'Gisborne',
    containedTerritories: [
      'Awapuni, Gisborne',
      'Elgin, Gisborne',
      'Gisborne, Gisborne',
      'Kaiti, Gisborne',
      'Mangapapa, Gisborne',
      'Okitu, Gisborne',
      'Ōpōtiki, Gisborne',
      'Outer Kaiti, Gisborne',
      'Riversdale, Gisborne',
      'Tamarau, Gisborne',
      'Taruheru, Gisborne',
      'Te Hapara, Gisborne',
      'Wainui, Gisborne',
      'Whataupoko, Gisborne'
    ]
  },
  {
    name: 'Hawke\'s Bay',
    containedTerritories: [
      'Akina, Hawke\'s Bay',
      'Bluff Hill, Hawke\'s Bay',
      'Camberley, Hawke\'s Bay',
      'Clive, Hawke\'s Bay',
      'Dannevirke, Hawke\'s Bay',
      'Flaxmere, Hawke\'s Bay',
      'Greenmeadows, Hawke\'s Bay',
      'Hastings, Hawke\'s Bay',
      'Haumoana, Hawke\'s Bay',
      'Havelock North, Hawke\'s Bay',
      'Hospital Hill, Hawke\'s Bay',
      'Mahora, Hawke\'s Bay',
      'Maraenui, Hawke\'s Bay',
      'Marewa, Hawke\'s Bay',
      'Mayfair, Hawke\'s Bay',
      'Napier, Hawke\'s Bay',
      'Napier South, Hawke\'s Bay',
      'Ngamotu, Hawke\'s Bay',
      'North Clyde, Hawke\'s Bay',
      'Onekawa, Hawke\'s Bay',
      'Parkvale, Hawke\'s Bay',
      'Pirimai, Hawke\'s Bay',
      'Raureka, Hawke\'s Bay',
      'Saint Leonards, Hawke\'s Bay',
      'Tamatea, Hawke\'s Bay',
      'Taradale, Hawke\'s Bay',
      'Te Awanga, Hawke\'s Bay',
      'Waipukurau, Hawke\'s Bay',
      'Wairoa, Hawke\'s Bay',
      'Westshore, Hawke\'s Bay'
    ]
  },
  {
    name: 'Marlborough',
    containedTerritories: [
      'Blenheim, Marlborough',
      'Burleigh, Marlborough',
      'Farnham, Marlborough',
      'Kaikōura, Marlborough',
      'Mayfield, Marlborough',
      'Picton, Marlborough',
      'Redwoodtown, Marlborough',
      'Riversdale, Marlborough',
      'Roselands, Marlborough',
      'Springlands, Marlborough',
      'Wither Rise, Marlborough',
      'Witherlea, Marlborough',
      'Yelverton, Marlborough'
    ]
  },
  {
    name: 'Nelson',
    containedTerritories: [
      'Annesbrook, Nelson',
      'Atawhai, Nelson',
      'Beachville, Nelson',
      'Bishopdale, Nelson',
      'Britannia Heights, Nelson',
      'Brooklands, Nelson',
      'Dodson Valley, Nelson',
      'Enner Glynn, Nelson',
      'Granity, Nelson',
      'Hampden, Nelson',
      'Maitai, Nelson',
      'Maitlands, Nelson',
      'Marybank, Nelson',
      'Moana, Nelson',
      'Monaco, Nelson',
      'Motueka, Nelson',
      'Murchison, Nelson',
      'Nayland, Nelson',
      'Nelson, Nelson',
      'Nelson East, Nelson',
      'Nelson South, Nelson',
      'Reefton, Nelson',
      'Richmond, Nelson',
      'Stephneyville, Nelson',
      'Stoke, Nelson',
      'Tāhunanui, Nelson',
      'The Brook, Nelson',
      'The Wood, Nelson',
      'Toi Toi, Nelson',
      'Torea, Nelson',
      'Tūī Glen, Nelson',
      'Wakatu, Nelson',
      'Washington Valley, Nelson',
      'Westport, Nelson'
    ]
  },
  {
    name: 'North Auckland',
    containedTerritories: [
      'Ahipara, North Auckland',
      'Albany, North Auckland',
      'Albany Heights, North Auckland',
      'Arch Hill, North Auckland',
      'Arkles Bay, North Auckland',
      'Auckland, North Auckland',
      'Avondale, North Auckland',
      'Awaroa Creek, North Auckland',
      'Balmoral, North Auckland',
      'Bayswater, North Auckland',
      'Bayview, North Auckland',
      'Beach Haven, North Auckland',
      'Beachlands, North Auckland',
      'Belmont, North Auckland',
      'Birkdale, North Auckland',
      'Birkenhead, North Auckland',
      'Blockhouse Bay, North Auckland',
      'Botany Downs, North Auckland',
      'Browns Bay, North Auckland',
      'Bucklands Beach, North Auckland',
      'Campbells Bay, North Auckland',
      'Castor Bay, North Auckland',
      'Chatswood, North Auckland',
      'Cheltenham, North Auckland',
      'Cockle Bay, North Auckland',
      'Conifer Grove, North Auckland',
      'Dargaville, North Auckland',
      'Devonport, North Auckland',
      'East Tamaki, North Auckland',
      'Eastern Beach, North Auckland',
      'Eden Terrace, North Auckland',
      'Ellerslie, North Auckland',
      'Epsom, North Auckland',
      'Fairview Heights, North Auckland',
      'Farm Cove, North Auckland',
      'Favona, North Auckland',
      'Flat Bush, North Auckland',
      'Forrest Hill, North Auckland',
      'Freemans Bay, North Auckland',
      'Glen Eden, North Auckland',
      'Glen Innes, North Auckland',
      'Glendene, North Auckland',
      'Glendowie, North Auckland',
      'Glenfield, North Auckland',
      'Grafton, North Auckland',
      'Green Bay, North Auckland',
      'Greenhithe, North Auckland',
      'Greenlane, North Auckland',
      'Grey Lynn, North Auckland',
      'Half Moon Bay, North Auckland',
      'Hauraki, North Auckland',
      'Henderson, North Auckland',
      'Herne Bay, North Auckland',
      'Highbury, North Auckland',
      'Highland Park, North Auckland',
      'Hikurangi, North Auckland',
      'Hillcrest, North Auckland',
      'Hillsborough, North Auckland',
      'Homai, North Auckland',
      'Horahora, North Auckland',
      'Howick, North Auckland',
      'Kaikohe, North Auckland',
      'Kaitaia, North Auckland',
      'Kamo, North Auckland',
      'Kawakawa, North Auckland',
      'Kelston, North Auckland',
      'Kensington, North Auckland',
      'Kerikeri, North Auckland',
      'Kingsland, North Auckland',
      'Kohimarama, North Auckland',
      'Konini, North Auckland',
      'Kumeū, North Auckland',
      'Lincoln, North Auckland',
      'Long Bay, North Auckland',
      'Lucas Heights, North Auckland',
      'Lynfield, North Auckland',
      'Mairangi Bay, North Auckland',
      'Mairtown, North Auckland',
      'Mangawhai Heads, North Auckland',
      'Mangawhare, North Auckland',
      'Māngere, North Auckland',
      'Māngere Bridge, North Auckland',
      'Māngere East, North Auckland',
      'Manukau City Centre, North Auckland',
      'Manurewa, North Auckland',
      'Manurewa East, North Auckland',
      'Marlborough, North Auckland',
      'Massey, North Auckland',
      'Massey East, North Auckland',
      'Massey West, North Auckland',
      'Massey-Birdwood, North Auckland',
      'Maunu, North Auckland',
      'McLaren Park, North Auckland',
      'Meadowbank, North Auckland',
      'Mechanics Bay, North Auckland',
      'Mellons Bay, North Auckland',
      'Middlemore, North Auckland',
      'Milford, North Auckland',
      'Mission Bay, North Auckland',
      'Moerewa, North Auckland',
      'Morningside, North Auckland',
      'Morningside, North Auckland',
      'Mount Albert, North Auckland',
      'Mount Eden, North Auckland',
      'Mount Roskill, North Auckland',
      'Mount Wellington, North Auckland',
      'Murray Bay, North Auckland',
      'Murrays Bay, North Auckland',
      'Narrow Neck, North Auckland',
      'New Lynn, North Auckland',
      'New Windsor, North Auckland',
      'Newmarket, North Auckland',
      'Newton, North Auckland',
      'North Titirangi, North Auckland',
      'Northcote, North Auckland',
      'Northcote Central, North Auckland',
      'Northcote Point, North Auckland',
      'Northcross, North Auckland',
      'Okura, North Auckland',
      'One Tree Hill, North Auckland',
      'Onehunga, North Auckland',
      'Onerahi, North Auckland',
      'Orakei, North Auckland',
      'Oranga, North Auckland',
      'Ōtāhuhu, North Auckland',
      'Otangarei, North Auckland',
      'Ōtara, North Auckland',
      'Oteha, North Auckland',
      'Owairaka, North Auckland',
      'Pahurehure, North Auckland',
      'Paihia, North Auckland',
      'Pakuranga, North Auckland',
      'Pakuranga Heights, North Auckland',
      'Panmure, North Auckland',
      'Papakura, North Auckland',
      'Papatoetoe, North Auckland',
      'Parakai, North Auckland',
      'Paremoremo, North Auckland',
      'Parnell, North Auckland',
      'Penrose, North Auckland',
      'Pinehill, North Auckland',
      'Point Chevalier, North Auckland',
      'Point England, North Auckland',
      'Pōkeno, North Auckland',
      'Ponsonby, North Auckland',
      'Pukekohe, North Auckland',
      'Raumanga, North Auckland',
      'Red Hill, North Auckland',
      'Remuera, North Auckland',
      'Remuwera, North Auckland',
      'Riverside, North Auckland',
      'Rosedale, North Auckland',
      'Rothesay Bay, North Auckland',
      'Royal Oak, North Auckland',
      'Saint Heliers, North Auckland',
      'Saint Johns, North Auckland',
      'Saint Marys Bay, North Auckland',
      'Sandringham, North Auckland',
      'Schnapper Rock, North Auckland',
      'Shelly Park, North Auckland',
      'Sherwood Rise, North Auckland',
      'Southdown, North Auckland',
      'St Johns, North Auckland',
      'Stanley Bay, North Auckland',
      'Stanley Point, North Auckland',
      'Stonefields, North Auckland',
      'Sunnyhills, North Auckland',
      'Sunnynook, North Auckland',
      'Sunnyvale, North Auckland',
      'Takapuna, North Auckland',
      'Tamaki, North Auckland',
      'Te Atatu North, North Auckland',
      'Te Atatū Peninsula, North Auckland',
      'Te Atatū South, North Auckland',
      'Te Papapa, North Auckland',
      'Three Kings, North Auckland',
      'Tikipunga, North Auckland',
      'Titirangi, North Auckland',
      'Torbay, North Auckland',
      'Totara Vale, North Auckland',
      'Tuakau, North Auckland',
      'Unsworth Heights, North Auckland',
      'Vauxhall, North Auckland',
      'Wai o Taiki Bay, North Auckland',
      'Waiake, North Auckland',
      'Waikowhai, North Auckland',
      'Waima, North Auckland',
      'Waimauku, North Auckland',
      'Wairau Valley, North Auckland',
      'Waitakere, North Auckland',
      'Waitakerei, North Auckland',
      'Warkworth, North Auckland',
      'Waterview, North Auckland',
      'Wattle Downs, North Auckland',
      'Wesley, North Auckland',
      'West Harbour, North Auckland',
      'Western Heights, North Auckland',
      'Western Springs, North Auckland',
      'Westfield, North Auckland',
      'Westgate, North Auckland',
      'Westmere, North Auckland',
      'Weymouth, North Auckland',
      'Whangaparāoa, North Auckland',
      'Whau Valley, North Auckland',
      'Windsor Park, North Auckland',
      'Wiri, North Auckland',
      'Woodhill, North Auckland',
      'Woodlands Park, North Auckland'
    ]
  },
  {
    name: 'Otago',
    containedTerritories: [
      'Abbotsford, Otago',
      'Andersons Bay, Otago',
      'Awamoa, Otago',
      'Balaclava, Otago',
      'Balclutha, Otago',
      'Belleknowes, Otago',
      'Boydtown, Otago',
      'Bradford, Otago',
      'Bridge Hill, Otago',
      'Brockville, Otago',
      'Buckleys Hill, Otago',
      'Burnside, Otago',
      'Calton Hill, Otago',
      'Cape Wanbrow, Otago',
      'Casa Nova, Otago',
      'Caversham, Otago',
      'Challis, Otago',
      'Clyde Hill, Otago',
      'Collinswood, Otago',
      'Concord, Otago',
      'Corstorphine, Otago',
      'Dalmore, Otago',
      'Dunedin, Otago',
      'Eveline, Otago',
      'Fernbrook, Otago',
      'Fernhill, Otago',
      'Frankton, Otago',
      'Glendale, Otago',
      'Green Island, Otago',
      'Halfway Bush, Otago',
      'Harington Point, Otago',
      'Helensbrook, Otago',
      'Helensburgh, Otago',
      'Holmes Hill, Otago',
      'Kaikorai, Otago',
      'Kenmure, Otago',
      'Kensington, Otago',
      'Kew, Otago',
      'Lake Ohau Alpine Village, Otago',
      'Liberton, Otago',
      'Lookout Point, Otago',
      'Maia, Otago',
      'Maori Hill, Otago',
      'Maryhill, Otago',
      'Meadowbank, Otago',
      'Mornington, Otago',
      'Mosgiel, Otago',
      'Mount Mera, Otago',
      'Musselburgh, Otago',
      'Normanby, Otago',
      'North Dunedin, Otago',
      'North East Valley, Otago',
      'Oamaru, Otago',
      'Ocean Grove, Otago',
      'Ocean View, Otago',
      'Opoho, Otago',
      'Otematata, Otago',
      'Owaka, Otago',
      'Pembroke, Otago',
      'Pine Hill, Otago',
      'Port Chalmers, Otago',
      'Portobello, Otago',
      'Queenstown, Otago',
      'Ravensbourne, Otago',
      'Redcastle, Otago',
      'Roslyn, Otago',
      'Saint Clair, Otago',
      'Saint Kilda, Otago',
      'Saint Leonards, Otago',
      'Sawyers Bay, Otago',
      'Shiel Hill, Otago',
      'South Dunedin, Otago',
      'South Hill, Otago',
      'South Oamaru, Otago',
      'St Clair Park, Otago',
      'Sunnyvale, Otago',
      'Sunshine, Otago',
      'Sunshine Bay, Otago',
      'Tainui, Otago',
      'Tomahawk, Otago',
      'Vauxhall, Otago',
      'Wakari, Otago',
      'Wanaka, Otago',
      'Waverley, Otago',
      'Woodhaugh, Otago'
    ]
  },
  {
    name: 'South Auckland',
    containedTerritories: [
      'Amisfield, South Auckland',
      'Aotea, South Auckland',
      'Arataki, South Auckland',
      'Avalon, South Auckland',
      'Bader, South Auckland',
      'Beerescourt, South Auckland',
      'Bellevue, South Auckland',
      'Bethlehem, South Auckland',
      'Brookfield, South Auckland',
      'Chartwell, South Auckland',
      'Chedworth, South Auckland',
      'Claudelands, South Auckland',
      'Deanwell, South Auckland',
      'Dinsdale, South Auckland',
      'Enderley, South Auckland',
      'Fairfield, South Auckland',
      'Fairview Downs, South Auckland',
      'Fenton Park, South Auckland',
      'Fitzroy, South Auckland',
      'Flagstaff, South Auckland',
      'Fordlands, South Auckland',
      'Forest Lake, South Auckland',
      'Frankton, South Auckland',
      'Gate Pa, South Auckland',
      'Glenholme, South Auckland',
      'Glenview, South Auckland',
      'Gradwell, South Auckland',
      'Grandview Heights, South Auckland',
      'Greerton, South Auckland',
      'Hamilton, South Auckland',
      'Hamilton Central, South Auckland',
      'Hamilton East, South Auckland',
      'Hamilton Lake, South Auckland',
      'Hamilton North, South Auckland',
      'Hamilton West, South Auckland',
      'Hannahs Bay, South Auckland',
      'Harrowfield, South Auckland',
      'Hillcrest, South Auckland',
      'Hillcrest, South Auckland',
      'Holdens Bay, South Auckland',
      'Huntington, South Auckland',
      'Huntly West, South Auckland',
      'Judea, South Auckland',
      'Katikati, South Auckland',
      'Kawaha Point, South Auckland',
      'Kawerau, South Auckland',
      'Kawhia, South Auckland',
      'Kihikihi, South Auckland',
      'Koutu, South Auckland',
      'Leamington, South Auckland',
      'Livingstone, South Auckland',
      'Lynmore, South Auckland',
      'Maeroa, South Auckland',
      'Mangakakahi, South Auckland',
      'Mangakino, South Auckland',
      'Matamata, South Auckland',
      'Matapuna, South Auckland',
      'Matarawa, South Auckland',
      'Matatā, South Auckland',
      'Matipo Heights, South Auckland',
      'Matua, South Auckland',
      'Melville, South Auckland',
      'Minginui, South Auckland',
      'Moanataiari, South Auckland',
      'Motuoapa, South Auckland',
      'Motuopa, South Auckland',
      'Mount Maunganui, South Auckland',
      'Murapara, South Auckland',
      'Murupara, South Auckland',
      'Nawton, South Auckland',
      'Ngapuna, South Auckland',
      'Ngāruawāhia, South Auckland',
      'Ngongotahā, South Auckland',
      'Nukuhau, South Auckland',
      'Ohinemutu, South Auckland',
      'Ohinenoutu, South Auckland',
      'Omanu, South Auckland',
      'Omanu Beach, South Auckland',
      'Otumoetai, South Auckland',
      'Otūmoetai, South Auckland',
      'Ōwhata, South Auckland',
      'Paeroa, South Auckland',
      'Papamoa Beach, South Auckland',
      'Papanui, South Auckland',
      'Paraonui, South Auckland',
      'Parawai, South Auckland',
      'Parkdale, South Auckland',
      'Parkvale, South Auckland',
      'Pleasant Heights, South Auckland',
      'Poike, South Auckland',
      'Pomare, South Auckland',
      'Pukehangi, South Auckland',
      'Pukete, South Auckland',
      'Putāruru, South Auckland',
      'Queenwood, South Auckland',
      'Rainbow Point, South Auckland',
      'Rangoroa, South Auckland',
      'Richmond Heights, South Auckland',
      'Riverlea, South Auckland',
      'Rotoehu Forest Village, South Auckland',
      'Rototuna, South Auckland',
      'Rototuna North, South Auckland',
      'Selwyn Heights, South Auckland',
      'Silverdale, South Auckland',
      'Springfield, South Auckland',
      'St Andrews, South Auckland',
      'Starrtown, South Auckland',
      'Strathmore, South Auckland',
      'Sunnybrook, South Auckland',
      'Tauhara, South Auckland',
      'Tauhara, South Auckland',
      'Taupō, South Auckland',
      'Tauranga Central, South Auckland',
      'Tauranga South, South Auckland',
      'Te Aroha, South Auckland',
      'Te Awamutu, South Auckland',
      'Te Kuiti, South Auckland',
      'Te Maunga, South Auckland',
      'Te Puke, South Auckland',
      'Te Rapa, South Auckland',
      'Te Rapa Park, South Auckland',
      'Te Reti, South Auckland',
      'Temple View, South Auckland',
      'Thames, South Auckland',
      'Thames North, South Auckland',
      'Tihiotonga, South Auckland',
      'Tīrau, South Auckland',
      'Tokoroa, South Auckland',
      'Tokoroa Central, South Auckland',
      'Totara Heights, South Auckland',
      'Utuhina, South Auckland',
      'Waipahihi, South Auckland',
      'Western Heights, South Auckland',
      'Western Heights, South Auckland',
      'Westmere, South Auckland',
      'Whakarewarewa, South Auckland',
      'Whakatāne, South Auckland',
      'Whangamatā, South Auckland',
      'Wharekaho, South Auckland',
      'Wharewaka, South Auckland',
      'Whitiora, South Auckland'
    ]
  },
  {
    name: 'South Auckland, Taranaki, Wellington',
    containedTerritories: [
      'Taumarunui, South Auckland, Taranaki, Wellington'
    ]
  },
  {
    name: 'Southland',
    containedTerritories: [
      'Appleby, Southland',
      'Avenal, Southland',
      'Bluff, Southland',
      'Clifton, Southland',
      'Colac, Southland',
      'Colac Bay/Ōraka, Southland',
      'East End, Southland',
      'East Gore, Southland',
      'Georgetown, Southland',
      'Gladstone, Southland',
      'Glengarry, Southland',
      'Grasmere, Southland',
      'Hawthorndale, Southland',
      'Heidelberg, Southland',
      'Invercargill, Southland',
      'Jacobs Town, Southland',
      'Kew, Southland',
      'Kingswell, Southland',
      'Makarewa, Southland',
      'Makerewa Township, Southland',
      'Newfield, Southland',
      'Oraka, Southland',
      'Richmond, Southland',
      'Riverton, Southland',
      'Riverton/Aparima, Southland',
      'Rockdale, Southland',
      'Rosedale, Southland',
      'Strathern, Southland',
      'The Rocks, Southland',
      'Tisbury, Southland',
      'Waihopai, Southland',
      'Waikiwi, Southland',
      'Waverley, Southland',
      'West End, Southland',
      'West Gore, Southland',
      'West Invercargill, Southland',
      'Windsor, Southland'
    ]
  },
  {
    name: 'Taranaki',
    containedTerritories: [
      'Bell Block, Taranaki',
      'Blagdon, Taranaki',
      'Brooklands, Taranaki',
      'East End, Taranaki',
      'Ferndale, Taranaki',
      'Fitzroy, Taranaki',
      'Frankleigh Park, Taranaki',
      'Glen Avon, Taranaki',
      'Hāwera, Taranaki',
      'Highlands Park, Taranaki',
      'Hospital Hill, Taranaki',
      'Hurdon, Taranaki',
      'Lynmouth, Taranaki',
      'Marfell, Taranaki',
      'Merrilands, Taranaki',
      'Moturoa, Taranaki',
      'New Plymouth, Taranaki',
      'Nolantown, Taranaki',
      'Ōakura, Taranaki',
      'Ōpunake, Taranaki',
      'Spotswood, Taranaki',
      'Strandon, Taranaki',
      'Stratford, Taranaki',
      'Te Whai-taranui-a-Whare-Matangi-ki-te-kimi-i-tana-matua-a-Ngarue, Taranaki',
      'Turuturu, Taranaki',
      'Vogeltown, Taranaki',
      'Waitara, Taranaki',
      'Welbourn, Taranaki',
      'Westown, Taranaki',
      'Whalers Gate, Taranaki'
    ]
  },
  {
    name: 'Wellington',
    containedTerritories: [
      'Alicetown, Wellington',
      'Aotea, Wellington',
      'Aramoho, Wellington',
      'Aro Valley, Wellington',
      'Ascot Park, Wellington',
      'Avalon, Wellington',
      'Awapuni, Wellington',
      'Bastia Hill, Wellington',
      'Belmont, Wellington',
      'Berhampore, Wellington',
      'Birchville, Wellington',
      'Boulcott, Wellington',
      'Breaker Bay, Wellington',
      'Broadmeadows, Wellington',
      'Brooklyn, Wellington',
      'Brown Owl, Wellington',
      'Camborne, Wellington',
      'Cannons Creek, Wellington',
      'Carterton, Wellington',
      'Cashmere, Wellington',
      'Castlecliff, Wellington',
      'Chartwell, Wellington',
      'Churton Park, Wellington',
      'Cloverlea, Wellington',
      'Crofton Downs, Wellington',
      'Days Bay, Wellington',
      'Durie Hill, Wellington',
      'Eastbourne, Wellington',
      'Elsdon, Wellington',
      'Epuni, Wellington',
      'Fairfield, Wellington',
      'Featherston, Wellington',
      'Fitzherbert, Wellington',
      'Foxton Beach, Wellington',
      'Glenside, Wellington',
      'Golden Gate, Wellington',
      'Gonville, Wellington',
      'Gracefield, Wellington',
      'Greenacres, Wellington',
      'Grenada North, Wellington',
      'Grenada Village, Wellington',
      'Greytown, Wellington',
      'Happy Valley, Wellington',
      'Harbour View, Wellington',
      'Hataitai, Wellington',
      'Heretaunga, Wellington',
      'Highbury, Wellington',
      'Highbury, Wellington',
      'Highland Park, Wellington',
      'Hokowhitu, Wellington',
      'Houghton Bay, Wellington',
      'Island Bay, Wellington',
      'Johnsonville, Wellington',
      'Johnsonville East, Wellington',
      'Karehana Bay, Wellington',
      'Karori, Wellington',
      'Karori West, Wellington',
      'Kelburn, Wellington',
      'Kelson, Wellington',
      'Kelvin Grove, Wellington',
      'Kenepuru, Wellington',
      'Khandallah, Wellington',
      'Kilbirnie, Wellington',
      'Kingsley Heights, Wellington',
      'Kingston, Wellington',
      'Korokoro, Wellington',
      'Kowhai Park, Wellington',
      'Kuratau, Wellington',
      'Lambton, Wellington',
      'Levin, Wellington',
      'Linden, Wellington',
      'Lindenvale, Wellington',
      'Lowry Bay, Wellington',
      'Lyall Bay, Wellington',
      'Māhina Bay, Wellington',
      'Mana, Wellington',
      'Manawatu Heads, Wellington',
      'Manor Park, Wellington',
      'Maoribank, Wellington',
      'Martinborough, Wellington',
      'Masterton, Wellington',
      'Maungaraki, Wellington',
      'Maupuia, Wellington',
      'Melrose, Wellington',
      'Milson, Wellington',
      'Miramar, Wellington',
      'Mitchelltown, Wellington',
      'Moera, Wellington',
      'Mornington, Wellington',
      'Mount Cook, Wellington',
      'Mount Victoria, Wellington',
      'Newlands, Wellington',
      'Newtown, Wellington',
      'Ngaio, Wellington',
      'Normandale, Wellington',
      'Northland, Wellington',
      'Ohakune, Wellington',
      'Ohariu, Wellington',
      'Oriental Bay, Wellington',
      'Ōtaki, Wellington',
      'Ōtaki Beach, Wellington',
      'Owhariu, Wellington',
      'Ōwhiro Bay, Wellington',
      'Paekākāriki, Wellington',
      'Pahautanui, Wellington',
      'Palmerston North, Wellington',
      'Papakowhai, Wellington',
      'Papakōwhai, Wellington',
      'Paparangi, Wellington',
      'Paraparaumu, Wellington',
      'Paraparaumu Beach, Wellington',
      'Paremata, Wellington',
      'Pauatahanui, Wellington',
      'Pāuatahanui, Wellington',
      'Petone, Wellington',
      'Pinehaven, Wellington',
      'Plimmerton, Wellington',
      'Point Howard, Wellington',
      'Porirua City, Wellington',
      'Porirua City Centre, Wellington',
      'Porirua East, Wellington',
      'Pukerua Bay, Wellington',
      'Raetihi, Wellington',
      'Rangoon Heights, Wellington',
      'Rānui, Wellington',
      'Ranui Heights, Wellington',
      'Raroa, Wellington',
      'Raumati Beach, Wellington',
      'Raumati South, Wellington',
      'Redwood, Wellington',
      'Riverstone Terraces, Wellington',
      'Rongotai, Wellington',
      'Roseneath, Wellington',
      'Roslyn, Wellington',
      'Saint Johns Hill, Wellington',
      'Seatoun, Wellington',
      'Seatoun Heights, Wellington',
      'Seaview, Wellington',
      'Silverstream, Wellington',
      'Solway, Wellington',
      'Southgate, Wellington',
      'Southgate, Wellington',
      'Springvale, Wellington',
      'Stokes Valley, Wellington',
      'Strathmore Park, Wellington',
      'Summerhill, Wellington',
      'Sundale, Wellington',
      'Taihape, Wellington',
      'Taitā, Wellington',
      'Taitville, Wellington',
      'Takapūwāhia, Wellington',
      'Takaro, Wellington',
      'Taupahi, Wellington',
      'Tawa, Wellington',
      'Te Aro, Wellington',
      'Terrace End, Wellington',
      'Thorndon, Wellington',
      'Timberlea, Wellington',
      'Tirohanga, Wellington',
      'Titahi Bay, Wellington',
      'Tītahi Bay, Wellington',
      'Tōtara Park, Wellington',
      'Trentham, Wellington',
      'Tūrangi, Wellington',
      'Upper Hutt, Wellington',
      'Vogeltown, Wellington',
      'Wadestown, Wellington',
      'Waikanae, Wellington',
      'Waikanae Beach, Wellington',
      'Wainuiomata, Wellington',
      'Waiouru, Wellington',
      'Waitangirua, Wellington',
      'Wallaceville, Wellington',
      'Wanganui East, Wellington',
      'Waterloo, Wellington',
      'Wellington, Wellington',
      'West End, Wellington',
      'Westhaven, Wellington',
      'Whitby, Wellington',
      'Wilton, Wellington',
      'Woburn, Wellington',
      'York Bay, Wellington'
    ]
  },
  {
    name: 'Westland',
    containedTerritories: [
      'Blaketown, Westland',
      'Cobden, Westland',
      'Dunollie, Westland',
      'Greymouth, Westland',
      'Haast, Westland',
      'Haast Beach, Westland',
      'Hokitika, Westland',
      'Karoro, Westland',
      'Seaview, Westland',
      'Wataroa, Westland',
      'Whataroa, Westland'
    ]
  },
  {
    name: 'Online', // special location, i.e. online volunteer opportunities
    containedTerritories: []
  }
]

// construct a list of territories from the regions
const territories = regions.map(r => r.containedTerritories).reduce((acc, val) => {
  return [...acc, ...val]
})

const sortedLocations = [
  ...regions.map(r => r.name),
  ...territories
]
sortedLocations.sort((l1, l2) => {
  if (l1 < l2) {
    return -1
  } else if (l1 > l2) {
    return 1
  } else {
    return 0
  }
})

module.exports = {
  regions,
  territories,
  sortedLocations
}
