const badges = [{
  entityType: 'BadgeClass',
  entityId: 'Random',
  openBadgeId: 'https://api.badgr.io/public/badges/HhIer_mgTtahY6TRT22L5A',
  createdAt: '2019-09-11T02:34:48Z',
  createdBy: 'asdfasdasdavds',
  issuer: 'asasdfjasdfhasodfaodf',
  issuerOpenBadgeId: 'https://networksolutions.com/som',
  name: 'React expert',
  image: 'https://media1.giphy.com/media/DiiQyFONn5sL6/giphy.gif',
  description: 'Only issue if the person know React',
  criteriaUrl: null,
  criteriaNarrative: 'Used React before duh',
  alignments: [],
  tags: [],
  expires: { amount: null, duration: null },
  extensions: {}
},
{
  entityType: 'BadgeClass',
  entityId: 'RANDOM',
  openBadgeId: 'https://api.badgr.io/public/badges/RANDOM',
  createdAt: '2019-09-14T21:42:17Z',
  createdBy: 'hAASDFASDJH',
  issuer: 'ASIDUFHASDIUFH',
  issuerOpenBadgeId: 'https://api.badgr.io/public/issuers/blabla',
  name: 'First class cunt',
  image: 'https://media1.giphy.com/media/DiiQyFONn5sL6/giphy.gif',
  description: 'Hell yeah',
  criteriaUrl: null,
  criteriaNarrative: 'Yeah',
  alignments: [],
  tags: [],
  expires: { amount: null, duration: null },
  extensions: {}
},
{
  entityType: 'BadgeClass',
  entityId: 'qkNkAH2FRXWOQVPnnnhojg',
  openBadgeId: 'https://over-blog.com',
  createdAt: '2019-09-15T00:22:13Z',
  createdBy: 'asdfadfasdf-WOhdjo7w',
  issuer: 'aSBVfm84SMasdfasdfiF0c16O9jCOA',
  issuerOpenBadgeId: 'https://over-blog.com',
  name: 'SuperStar',
  image: 'https://media1.giphy.com/media/DiiQyFONn5sL6/giphy.gif',
  description: 'You are a super star!',
  criteriaUrl: null,
  criteriaNarrative:
        'This person shows other people respect and puts the other persons interests before their own',
  alignments: [],
  tags: [],
  expires: { amount: null, duration: null },
  extensions: {}
},
{
  entityType: 'BadgeClass',
  entityId: '0N1IKYUXSE6lDKcPn8mX5A',
  openBadgeId: 'https://admin.chd',
  createdAt: '2019-09-15T03:04:21Z',
  createdBy: 'fNaJaIYtsdfsdfsdTrORi3BjWf9_Ag',
  issuer: 'aSBVfm84SMiF0csdasdfsdf16O9jCOA',
  issuerOpenBadgeId: 'https://admin.ch',
  name: 'Completed VP-82',
  image: 'https://media1.giphy.com/media/DiiQyFONn5sL6/giphy.gif',
  description: 'I have completed VP-82!',
  criteriaUrl: null,
  criteriaNarrative: 'I have completed VP-82!',
  alignments: [],
  tags: [],
  expires: { amount: null, duration: null },
  extensions: {}
}]

module.exports = badges
