#!/bin/bash
MY_DIR=$( dirname "${BASH_SOURCE[0]}" )

# login to signapore
source ${MY_DIR}/login-sydney

# restart
aws ecs update-service --service voluntarily-beta-service --cluster vly-beta --desired-count 3 --deployment-configuration maximumPercent=100,minimumHealthyPercent=50 --force-new-deployment 