#!/bin/bash
MY_DIR=$( dirname "${BASH_SOURCE[0]}" )

# Get a docker login and run it
source ${MY_DIR}/login-sydney

aws ecs update-service --service vly-alpha --cluster vly-alpha-ECSCluster --force-new-deployment --desired-count 3 --deployment-configuration maximumPercent=100,minimumHealthyPercent=50

